[package]
name = "ruthless"
version = "0.1.0"
authors = ["Ethan Jaszewski <ethanjaszewski@yahoo.com>"]

[dependencies]
time = "0.1"
clap = {version = "~2.27.0", features = ["yaml"]}

[profile.release]
debug = true
